name: data_management

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.adminCommand({ ping: 1 })' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  postgres:
    image: postgres:15
    container_name: postgres_db
    profiles: ["seed"]
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: data_management_pipeline
    volumes:
      - ./landing_zone:/app/landing_zone
    env_file:
      - ./.env
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=trusted_zone
      - RUN_MODE=app
      - POSTGRES_HOST=postgres
    depends_on:
      mongo:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: "no"
    profiles: ["seed"]

volumes:
  mongo_data:
  postgres_data: